#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# enforce conventional commit
green='\033[0;32m'
red='\033[0;31m'
clear='\033[0m'

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message does not follow the pattern: ^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))" >&2
    echo "A valid example is: ${green}'ci: :sparkles: enforce conventional commit using commit message hook'${clear}" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi

